### ISSUE TITLE
Alfred 2.0 support?

### ISSUE THREAD

**Issue by jeffbyrnes** [wouter-de-boer/iAlfredThis#3]
I just found this extension, and I'd love to see Alfred 2 support. Thanks!

**Comment by matthewmcvickar** [comment]
---

**Repository updated!**

At first I had directions here how to set this up in Alfred 2 by yourself, but I just discovered you can export Alfred 2 workflows, so I've done that and updated my repostory: https://github.com/matthewmcvickar/iAlfredThis

@jeffbyrnes Enjoy!

---

**The original, manual-setup instructions:**

Wouter de Vos and the Springest team made [a new version](http://devblog.springest.com/idonethis-from-the-command-line-with-the-idid-gem) of their iDoneThis utility as a gem that works on the command line. [The gem is on GitHub](https://github.com/foxycoder/idid) as well.

So you have two options:
1. Install [the `idid` gem](http://devblog.springest.com/idonethis-from-the-command-line-with-the-idid-gem), configure it, and make a Alfred 2 workflow that just sends your 'idid' or 'idone' Alfred query through to the command line, like in this screenshot:
   
   ![Screen Shot 2013-04-25 at 9 18 03pm](https://f.cloud.github.com/assets/200641/429444/5ec3dfc2-ae44-11e2-8936-248a48dd81c9.PNG)
   
   Now you can call up Alfred, type 'idid foo bar baz' and the text after 'idid' will be sent through the gem.
2. The simpler option is to copy over the basic PHP code from the old iAlfredThis into the new Alfred 2 workflow system. Just set up a workflow that runs a PHP script like this when you invoke the `idid` (or `idone`) keyword:
   
   ![Screen Shot 2013-04-25 at 9 39 27pm](https://f.cloud.github.com/assets/200641/429461/533914d2-ae45-11e2-82dd-45842abd95b2.PNG)
   
   The PHP code you need is:
   
   ```
   $to = 'today@idonethis.com';
   $subject = 'Re: Personal digest for ' . date("F d");
   $message = {query};
   $headers = "From: YOUR_IDONETHIS_EMAIL_ADDRESS \r\n";
   
   mail($to, $subject, $message, $headers);
   ```
   
   The only thing you need to customize there is the email address, which should be the exact same as the one with which  you'd respond to an iDoneThis daily checkin email.
   
   (I chose this method myself because I don't need the functionality of the `idid` gem or team/project capabilities; I only use it for sending iDoneThis records to my personal iDoneThis account.)

---

Let me know if you have any trouble setting that up.
